"""f_uid added

Revision ID: f5508565cbed
Revises: 
Create Date: 2025-10-31 15:38:17.478111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5508565cbed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theatre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('foreign_key', 'user', ['u_id'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theatre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('u_id')

    # ### end Alembic commands ###
